### ISSUE TITLE
How to add "Emoji" to Input or TextInput

### ISSUE THREAD

**Issue by bachbonglong** [liangl1412/react-native-emoji-keyboard#9]
What if I want to enter text from the keyboard or click "Emoji" at the same Input or TextInput?

**Comment by liangl1412** [comment]
You want do something like this 'wo:blush:rd'?

**Comment by bachbonglong** [comment]
> You want do something like this 'wo😊rd'?

Yes !!  Like chatting on messenger

**Comment by liangl1412** [comment]
Then you wouldn't be need this component, standard keyboard that prompt from ios or Android has text and emoji. This component is for emoji only. 
That being said, if you need this because you want add custom emoji, you can done by this way: 
1. Create normal Textinput
2. add another button that will toggle emoji board(you can position anywhere you see fit)
Now, when you active the Textinput, you will be typing letter as normal, if you feel you need to insert a emoji, you will need to click the button to toggle on the Emoji component, append the emoji you pick to the Textinput.
Hope that helps :)

**Comment by bachbonglong** [comment]
Thanks you so much ! It's work

**Comment by ArmanWhitestone** [comment]
emoji to click in open textinput to emojis same

**Comment by Okoli-Ryan** [comment]
But when you have a separate emoji keyboard, and you move the cursor to a different position, how do you handle that so the emoji is placed where the cursor is and not at the end of the text? Unless there is a "getCursorPosition" kind of thing in textinput

**Comment by sbattou** [comment]
> But when you have a separate emoji keyboard, and you move the cursor to a different position, how do you handle that so the emoji is placed where the cursor is and not at the end of the text? Unless there is a "getCursorPosition" kind of thing in textinput

@Okoli-Ryan have you found a solution?

**Comment by Okoli-Ryan** [comment]
No
